providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1693872184'

[variables]
NIXPACKS_METADATA = 'python'
NIXPACKS_POETRY_VERSION = '1.3.1'
PYTHONUNBUFFERED = '1'
[phases.install]
dependsOn = ['setup']
cmds = ['python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install .']
cacheDirectories = ['/root/.cache/pip']
paths = ['/opt/venv/bin']

[phases.setup]
nixPkgs = [
    'python310',
    'gcc',
]
nixLibs = [
    'zlib',
    'stdenv.cc.cc.lib',
]
nixOverlays = []
nixpkgsArchive = '293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847'

[start]
cmd = 'python main.py'

